In [ ]:
!pip install numpy
!pip install pandas

In [ ]:
import numpy as np
import pandas as pd

In [3]:
# The code below initializes a Python list named list1:
list1 = [1,2, 3, 4]
# To convert this to a one-dimensional ndarray with one row and four columns, we can use the np.array() function:
array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [7]:
# To get a two-dimensional ndarray from a list, we must start with a Python list of lists:
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# In the above output, you may notice that 
# the NumPy array print-out is displayed in a way 
# that clearly demonstrates its multi-dimensional structure: 
# two rows and three columns.

In [ ]:
# Mathematical operations can be performed on all values in a ndarray at one time rather than having to loop through values, 
# as is necessary with a Python list. This is very helpful in many scenarios. Say you own a toy store 
# and decide to decrease the price of all toys by €2 for a weekend sale. With the toy prices stored in an ndarray, 
# you can easily facilitate this operation.

In [8]:
toyPrices = np.array([5,7,8,9])
flat_rate = toyPrices - 2
print(flat_rate)

[3 5 6 7]


In [ ]:
# If, however, you had stored your toy prices in a Python list, you would have to manually loop through the entire list 
# to decrease each toy price.

In [10]:
toyPrices = [5,7,8,9]
for i in range(len(toyPrices)):
    toyPrices[i] -= 2
print(toyPrices)

[3, 5, 6, 7]


In [ ]:
# Pandas Series and Dataframes
# Just as the ndarray is the foundation of the NumPy library, the Series is the core object of the pandas library. 
# A pandas Series is very similar to a one-dimensional NumPy array, but it has additional functionality 
# that allows values in the Series to be indexed using labels. A NumPy array does not have the flexibility to do this. 
# This labeling is useful when you are storing pieces of data that have other data associated with them. 
# Say you want to store the ages of students in an online course to eventually figure out the average student age. 
# If stored in a NumPy array, you could only access these ages with the internal ndarray indices 0,1,2.... With a Series object, 
# the indices of values are set to 0,1,2... by default, but you can customize the indices to be other values 
# such as student names so an age can be accessed using a name. Customized indices of a Series are established 
# by sending values into the Series constructor, as you will see below.

# A Series holds items of any one data type and can be created by sending in a scalar value, Python list, dictionary, or ndarray 
# as a parameter to the pandas Series constructor. If a dictionary is sent in, the keys may be used as the indices.

In [11]:
# # Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)

0    13
1    25
2    19
dtype: int32


In [12]:
# # Create a Series using a NumPy array of ages but customize the indices to be the names that correspond to each age
ages = np.array([13,25,19])
series1 = pd.Series(ages, index=['Amit', 'Khokon', 'Sajib'])
print(series1)

Amit      13
Khokon    25
Sajib     19
dtype: int32


In [ ]:
# Another important type of object in the pandas library is the DataFrame. This object is similar in form to a matrix 
# as it consists of rows and columns. Both rows and columns can be indexed with integers or String names. 
# One DataFrame can contain many different types of data types, but within a column, everything has to be the same data type. 
# A column of a DataFrame is essentially a Series. All columns must have the same number of elements (rows).

# There are different ways to fill a DataFrame such as with a CSV file, a SQL query, a Python list, or a dictionary. 
# Here we have created a DataFrame using a Python list of lists. 
# Each nested list represents the data in one row of the DataFrame. 
# We use the keyword columns to pass in the list of our custom column names.

In [14]:
df = pd.DataFrame([
    ['Anowar','Pipla',42],
    ['Ripon','Khubjipur',42],
    ['Imrul','Khunjipur',42]
],
columns=['Name','Address','Age'])
print(df)

     Name    Address  Age
0  Anowar      Pipla   42
1   Ripon  Khubjipur   42
2   Imrul  Khunjipur   42


In [16]:
df.set_index('Name')

Address  Age
Name                  
Anowar      Pipla   42
Ripon   Khubjipur   42
Imrul   Khunjipur   42